### PR TITLE
Added Norwegian language

### PR DESCRIPTION
**Pull request by Allram**

### CODE REVIEW

**Comment by ArjanKranenburg** [comment]
Thanks for this. Very much apprectiated!

**Comment by ArjanKranenburg** [comment]
I've also added these capabilities:
        "meter_gas": "Gas Meter",
        "meter_water": "Water Meter",
        "meter_rain": "Rain Meter",
How would they translate in Norwegian?

**Comment by ArjanKranenburg** [comment]
How would you translate "Virtual Devices"? Is that "virtuell enhet"?
It is also mentioned in the app.json which is shown in the app-store.
And do you object being mentioned as translator for Norwegian? If not, which name shall I mention?

**Comment by Allram** [comment]
> I've also added these capabilities:
> "meter_gas": "Gas Meter",
> "meter_water": "Water Meter",
> "meter_rain": "Rain Meter",
> How would they translate in Norwegian?

> "meter_gas": "Gassmåler",
> "meter_water": "Vannmåler",
> "meter_rain": "Regnmåler",
> "Virtual Devices": "Virtuell enhet",

Do you just add them, or should i integrate them into this PR?

**Comment by Allram** [comment]
> How would you translate "Virtual Devices"? Is that "virtuell enhet"?
> It is also mentioned in the app.json which is shown in the app-store.
> And do you object being mentioned as translator for Norwegian? If not, which name shall I mention?

I can update the PR tonight with app.json app-store text and contributor :)

**Comment by ArjanKranenburg** [comment]
Super! Thank Vegard!

**Pull request merged**
